version: 2.1
orbs:
  node: circleci/node@5.1.0

parameters:
  is-destroy:
    type: boolean
    default: false
  target-env:
    type: string
    default: ""

jobs:
  install_packages:
    executor: 
      name: node/default
      tag: "16.19.1"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  plan_apply:
    docker:
      - image: cimg/node:16.19.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install cdktf-cli
          command: |
            npm install -g cdktf-cli@latest
      - run:
          name: Install Terraform
          command: |
            curl -O https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip
            unzip terraform_1.4.2_linux_amd64.zip
            mv terraform /usr/local/bin/
      - run:
          name: Terraform Plan
          command: |
            cdktf diff
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  apply:
    docker:
      - image: cimg/node:16.19.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install cdktf-cli
          command: |
            npm install -g cdktf-cli@latest
      - run:
          name: Install Terraform
          command: |
            curl -O https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip
            unzip terraform_1.4.2_linux_amd64.zip
            mv terraform /usr/local/bin/
      - run:
          name: Terraform Apply
          command: |
            cdktf deploy

workflows:
  plan_approve_apply_dev:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [ false, << pipeline.parameters.is-destroy >> ]
        - not:  << pipeline.parameters.target-env >> 
    jobs:
      - install_packages
      - plan_apply:
          requires:
            - install_packages
      - hold_apply:
          type: approval
          requires:
            - plan_apply
      - apply:
          requires:
            - hold_apply